Repository wecode-bootcamp-korea/29-1st-Apocalypse-frontend, pull requests merged in 2022-02, with the labels that each got.

#13 [29기 홍지은] 푸터
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterContent/FooterContent.js
  src/components/Footer/FooterContent/FooterContent.scss
Labels: Status: 추가 기능 구현중

#14 [29기 이화종]login mypage 수정
  src/Mypage/LoginMypage.js
  src/Mypage/LoginMypage.scss
  src/Mypage/LoginMypageMain.js
  src/Mypage/LoginMypageMain.scss
  src/Mypage/LoginOrderList.scss
  src/Router.js
Labels: Status: 추가 기능 구현중

#21 [29기 홍지은] 푸터
  src/Main/Main.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterContent/FooterContent.js
  src/components/Footer/footerData.js
Labels: Status: Conflict 해결 요청

#20 [29기 김기만] feature/Nav
  public/data/commentDataList.json
  public/data/commentDataListBasket.json
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavCompoenet/MyPage/MyPage.js
  src/components/Nav/NavCompoenet/Search/Search.js
  src/components/Nav/NavCompoenet/Search/Search.scss
  src/components/Nav/NavCompoenet/Search/Searching/MiddleSearch.js
  src/components/Nav/NavCompoenet/Search/Searching/Searching.js
  src/components/Nav/NavCompoenet/Shopping/Shopping.js
  src/components/Nav/NavCompoenet/Shopping/Shopping.scss
  src/components/Nav/NavCompoenet/Shopping/ShoppingList/Product.js
  src/components/Nav/NavCompoenet/Shopping/ShoppingList/ProductDetail.js
  src/components/Nav/NavCompoenet/Shopping/ShoppingList/ShoppingList.js
  src/components/Nav/NavCompoenet/Shopping/ShoppingList/ShoppingList.scss
  src/components/Nav/NavCompoenet/ShoppingBasket/BasketList/BaketList.js
  src/components/Nav/NavCompoenet/ShoppingBasket/BasketList/BasketList.scss
  src/components/Nav/NavCompoenet/ShoppingBasket/ShoppingBasket.js
  src/components/Nav/NavCompoenet/ShoppingBasket/ShoppingBasket.scss
  src/components/Nav/NavCompoenet/tendency/TendecyProduct.js
  src/components/Nav/NavCompoenet/tendency/Tendency.js
  src/components/Nav/NavCompoenet/tendency/Tendency.scss
  src/components/Nav/NavCompoenet/tendency/TendencyTest.js
  src/styles/thousand.js
Labels: Status: 리뷰 요청

#9 [29기 김기만] Feature/productDetailList
  src/Main/Main.js
  src/ProductDetailList/ProductDetailList.js
  src/ProductDetailList/ProductDetailList.scss
  src/ProductDetailList/ProductList/ProductList.js
  src/ProductDetailList/ProductList/ProductList.scss
  src/Router.js
  src/components/Nav/NavCompoenet/WishList/WishList.js
Labels: Status: 리뷰 요청

#16 [29기 이화종] 장바구니
  public/data/cartItem.json
  src/Cart/Cart.js
  src/Cart/Cart.scss
  src/Cart/CartProductList/CartProductList.js
  src/Cart/CartProductList/CartProductList.scss
  src/Main/Main.js
  src/Mypage/LoginOrderList.js
  src/Mypage/LoginOrderList.scss
  src/Mypage/LoginWishList.js
  src/Mypage/LoginWishList.scss
  src/Mypage/Mypage.scss
  src/Router.js
Labels: Status: 리뷰 요청

#26 [29기 홍지은] 메인 페이지
  src/Main/AddCartBtn/AddCartBtn.js
  src/Main/AddCartBtn/AddCartBtn.scss
  src/Main/Benefit/Benefit.js
  src/Main/Bookmark/Bookmark.js
  src/Main/Main.js
  src/Main/Main.scss
  src/Main/MainSlider/MainSlider.js
  src/Main/MainSlider/MainSlider.scss
  src/Main/MainSlider/MainSliderComp/MainSliderComp.js
  src/Main/MainSlider/MainSliderComp/MainSliderComp.scss
  src/Main/MainSlider/pics/main_1.jpeg
  src/Main/MainSlider/pics/main_2.jpeg
  src/Main/MainSlider/pics/main_3.jpeg
  src/Main/MediaAsset/MediaAsset.js
  src/Main/Modal/Modal.js
  src/Main/Modal/Modal.scss
  src/Main/Product/Product.js
  src/Main/Product/Product.scss
  src/Main/SoldOutBtn/SoldOutBtn.js
  src/Main/SoldOutBtn/SoldOutBtn.scss
  src/ProductDetailPage/AddCartBtn/AddCartBtn.js
  src/Router.js
Labels: Status: 리뷰 요청

#18 [29기 이화종] 오더리스트 레이아웃 구현
  src/Mypage/LoginOrderList.js
  src/Mypage/LoginOrderList.scss
Labels: Status: 리뷰 요청

#19 [29기 이화종] wishList
  src/Mypage/LoginMypage.js
  src/Mypage/LoginWishList.js
Labels: Status: 리뷰 요청

#22 [29기 박재형] Mypage
  src/Mypage/Mypage.scss
  src/Mypage/SigninPage.js
  src/Mypage/SigninPage.scss
  src/Mypage/SignupPage.js
  src/Mypage/SignupPage.scss
Labels: Status: 리뷰 요청

#27 [29기 홍지은] 제품 상세 페이지
  src/ProductDetailPage/AddCartBtn/AddCartBtn.js
  src/ProductDetailPage/Benefit/Benefit.js
  src/ProductDetailPage/Bookmark/Bookmark.js
  src/ProductDetailPage/Modal/Modal.js
  src/ProductDetailPage/Product/Product.js
  src/ProductDetailPage/Product/Product.scss
  src/ProductDetailPage/ProductDetailInfo/ProductDetailInfo.js
  src/ProductDetailPage/ProductDetailItem/ProductDetailItem.js
  src/ProductDetailPage/ProductDetailItem/ProductDetailItem.scss
  src/ProductDetailPage/ProductDetailPage.js
  src/ProductDetailPage/ProductDetailPage.scss
  src/ProductDetailPage/ProductDetailTop/ProductDetailTop.js
  src/ProductDetailPage/UseLocalStorage.js
  src/components/Footer/FooterContent/FooterContent.scss
Labels: Status: 리뷰 요청

#25 [29기 박재형]주문기능 레이아웃 및 배송지정보
  src/OrderPage/BillSummary.js
  src/OrderPage/BillSummary.scss
  src/OrderPage/Complete.js
  src/OrderPage/Complete.scss
  src/OrderPage/CompleteStatusComponent.js
  src/OrderPage/CompleteStatusComponent.scss
  src/OrderPage/CustomerService.js
  src/OrderPage/CustomerService.scss
  src/OrderPage/OrderPage.js
  src/OrderPage/OrderPage.scss
  src/OrderPage/OrderReview.js
  src/OrderPage/OrderReview.scss
  src/OrderPage/OrderReviewComponent.js
  src/OrderPage/OrderReviewComponent.scss
  src/OrderPage/OrderStatus.js
  src/OrderPage/OrderStatus.scss
  src/Router.js
Labels: Status: 리뷰 요청
